import "./globals.css";
import type { Metadata } from "next";
import { NavLink } from "@/shared/types";
import { Header } from "@/shared/components/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
function getMediaLinks(): NavLink[] | PromiseLike<NavLink[]> {
  throw new Error("Function not implemented.");
}
