import type { Metadata } from "next";
import "@/app/_ui/styles/global.css";
import { inter } from "@/app/_ui/fonts";
import { Header } from "@/app/_ui/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
