import "../styles/variables.css";
import "../styles/global.css";
import { Header, FranchisesCarousel } from "../components/layout";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <FranchisesCarousel />
        {children}
      </body>
    </html>
  );
}
