import "@/app/globals.css";
import type { Metadata } from "next";
import { getMediaLinks } from "./HomePage.service";
import { Header } from "@/shared/components/layout";
import { NavLink } from "@/shared/types";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navLinks: NavLink[] = await getMediaLinks();

  return (
    <html lang="pt-br">
      <body>
        <Header navLinks={navLinks} />
        <main>{children}</main>
      </body>
    </html>
  );
}
