import type { Metadata } from "next";
import "@/app/globals.css";
import { Header } from "@/components/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <Header />
      <body>{children}</body>
    </html>
  );
}
